use_frameworks!

platform :ios, '9.0'

target 'KWidgetProject_Example' do
  pod 'KWidgetProject', :path => '../'

  target 'KWidgetProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
